### ISSUE TITLE
Error adding first executive user

### ISSUE THREAD

**Issue by lsgs** [ui-icts/redcap-admin-dashboard#1]
I found I could not add an executive user because the `UIOWA_AdminDash.executiveUsers` array does not get initialised. You can't push a new element into `null`. 

![admindash-issue](https://user-images.githubusercontent.com/7444426/65396333-b4fad780-dde8-11e9-82a5-a34004c84ec1.png)

I worked around the problem by manually adding `executive-users` as an empty json array into redcap_external_modules_settings, and once one is added there is no problem with adding more.

![admindash-issue-workaround](https://user-images.githubusercontent.com/7444426/65396341-c93ed480-dde8-11e9-889e-f6b80f9c8688.png)

**Comment by izneuhaus** [comment]
Fixed!
