### ISSUE TITLE
[Question] I would like to export the Research projects

### ISSUE THREAD

**Issue by 274188A** [ui-icts/redcap-admin-dashboard#11]
Hi @chrisortman - I can't seem to find a way of re-configuring the `Research` Projects report to allow the results of the report to be exported.

Is it hard coded to disallow exporting?

TIA,

John

**Comment by uiowajs** [comment]
Hello,

What version of admin dashboard are you using?  This issue should be fixed in 4.0.5.

Thanks

**Comment by 274188A** [comment]
I'm on 4.05 already...

here's a screen shot:
![image](https://user-images.githubusercontent.com/40014477/152259355-a12acd4d-9fe5-43e6-945a-b20b1761a6d5.png)


`REDCap 12.2.1 · PHP 7.4.27 (Windows OS) · MySQL 8.0.28`

Thanks,
John

**Comment by 274188A** [comment]
**Enabled Module**
![image](https://user-images.githubusercontent.com/40014477/152444254-c35943e5-36bd-4422-b16a-56f11c703084.png)


**Showing module on Web Server**
![image](https://user-images.githubusercontent.com/40014477/152444943-5810ec14-30ad-4922-b992-c32621b8defe.png)

Cheers, 
John

**Comment by 274188A** [comment]
Just noticed there are a number of js errors showing tha are probably the cause of the situation.
What version(s) of php are compatible with this module?  I'm using `**7.4.27**`

![image](https://user-images.githubusercontent.com/40014477/152445427-94f3a415-f519-483a-b05f-6865d48725a0.png)

**Comment by uiowajs** [comment]
Hello,

A quick temporary fix is to change the column formatting for replacing standard codes with labels to "N/A"

![adminDashPurposeFix](https://user-images.githubusercontent.com/38951662/152581073-61d82a88-236f-48d5-be71-9f6c6e72d50b.PNG)

Let me know if this helps.


Thanks

**Comment by 274188A** [comment]
thanks - that fixed it
