### ISSUE TITLE
Status Dropdowns missing status "Completed"

### ISSUE THREAD

**Issue by 274188A** [ui-icts/redcap-admin-dashboard#12]
Hi Chris, @chrisortman  Could we have "Completed" added to the status filter dropdowns?

Happy to fix this myself if I can but not sure if it's configurable or hard coded for the table header filters:

![image](https://user-images.githubusercontent.com/40014477/152711982-9ad3899e-9f4e-4966-9c0c-1333170a286f.png)

Thanks!

**Comment by chrisortman** [comment]
I wonder if you can control this via the configuration project? @uiowajs  might know more?

**Comment by uiowajs** [comment]
Hello,

It seems that "completed" is a different value from the project status.  That is, "completed" isn't a project status.  I'll see what I can do about making it a choice in that column filter, but you may want to create a custom report with the "completed_time" column as a column.   


Thanks
