### ISSUE TITLE
SQL queries are not running since update to REDCap 14.3.2

### ISSUE THREAD

**Issue by pevmtss** [ui-icts/redcap-admin-dashboard#22]
After upgrade to REDCap 14.3.2 · PHP 8.0.30 (Linux/Unix OS) · MySQL 8.0.28, I am getting error messages on all reports. But project_id shouldn't have changed, unclear why this is not pulling the data. Running V 4.1.2 of EM

Error message:
DataTables warning: table id=reportTable_5 - Requested unknown parameter 'project_id' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

**Comment by frissner** [comment]
It seems that version 4.1.2 destroys the reusltset:
Steps to reproduce:
1.  open dashboard-project
2. select "Record Status Dashboard"
3. click on any SQL-Query
4. check entries in "colum names"
-> entries match column-names as defined in query (see below)
5. press "Test query"
6. check entries in "colum names" again
-> colum names are destroyed  (see below)

Tested on REDCap 14.0.26 · PHP 7.4.33 (Linux/Unix OS) · MariaDB 5.5.68
and REDCap 14.0.5 · PHP 8.0.30 (Linux/Unix OS) · MariaDB 10.3.39

------------------------------
before test-Query:
[
  "username",
  "user_lastname",
  "user_firstname",
  "user_email",
  "project_id#group#hidden",
  "app_title#group",
  "completed_time#group#hidden",
  "date_deleted#group#hidden",
  "project_id_count",
  "user_suspended_time#hidden",
  "status#group#hidden"
]


after test Query:
[
  "username;user_lastname;user_firstname;user_email;project_id#group#hidden;app_title#group;completed_time#group#hidden;date_deleted#group#hidden;project_id_count;user_suspended_time#hidden;status#group#hidden"
]

**Comment by shichikoromo** [comment]
My environment is also REDCap 14.0.5 · PHP 8.0.30 (Linux/Unix OS) · MariaDB 10.3.39.
I have the same problem with versions 4.1, 4.1.1 and 4.1.2, while with version 4.0.6 it did not happen.

**Comment by uiowajs** [comment]
This was an issue with REDCap database query tool returning an extra row of html in the data export
