### ISSUE TITLE
Error when enabling EM

### ISSUE THREAD

**Issue by jthomas08** [ui-icts/redcap-admin-dashboard#3]
When trying to enable the latest version on RC 9.5.x, I got the following error:
Failed opening required 'vendor/autoload.php'

Our RC installation does not have outbound access is that an issue?

**Comment by izneuhaus** [comment]
It sounds like you don't have the files normally included by Composer - did you install the module from the official REDCap Repo or get the source directly from here?

You can run `composer install` yourself or you can download this release zip with everything already included: https://github.com/ui-icts/redcap-admin-dashboard/releases/download/3.4.4/redcap-admin-dashboard-3.4.4-composer.zip

**Comment by jthomas08** [comment]
I manually downloaded the zip from here. Will the download from the RC repo have all the dependencies?

**Comment by izneuhaus** [comment]
Yep, the version in the Repo has everything included already.

**Comment by jthomas08** [comment]
Ok, is possible to have  a zip file with everything included? We typically to test other  EM's on a internal test server (unfortunately that server has no outbound access) and then move the EM to prod. We're wary about directly downloading to prod server (which is the only 1 with outbound access).

**Comment by izneuhaus** [comment]
https://github.com/ui-icts/redcap-admin-dashboard/releases/download/3.4.4/redcap-admin-dashboard-3.4.4-composer.zip
