### ISSUE TITLE
Authorization bypass

### ISSUE THREAD

**Issue by utiso** [ui-icts/redcap-admin-dashboard#8]
The end-point _/ExternalModules/?prefix=admin_dash&page=requestHandler&type=saveReportSettings_ does not verify that users POSTing to it have administrative access to REDCap itself. It was discovered when writing the JSON payload for ticket #6 that any logged-in user of REDCap could create new projects in the Admin Dashboard module. Combined with the XSS flaw, any user of REDCap can create and export data from the Admin Dashboard module. 

Please ensure that only authorized users can interact with this module.

**Comment by izneuhaus** [comment]
This is fixed in 3.5.3.
